### PR TITLE
feat(router): implement GoRouter navigation system

### PR DESCRIPTION
**Pull request by phoenixit99**
- Setup GoRouter configuration with initial routes • Create app_router.dart with route definitions • Define AppRoute enum for type-safe routing • Configure MaterialApp.router in main.dart

- Implement core screens with navigation flow • Add SplashScreen with 2-second auto-navigation • Create HomeScreen with basic layout • Setup proper back navigation handling

- Add comprehensive router tests • Test route paths and names validation • Verify navigation flow from splash to home • Ensure proper widget rendering • Test back navigation behavior

The implementation follows a feature-first structure and includes: • Type-safe route management
• Automatic navigation from splash to home
• Proper handling of back navigation
• Comprehensive test coverage

### CODE REVIEW

**Comment by esmaeil-ahmadipour** [comment]
@phoenixit99, please amend the commit to resolve the conflict and update the commit message. After making the changes, force-push the updated commit.

Screenshot from 2024-11-29 15-43-24

**Comment by phoenixit99** [comment]
> @phoenixit99, please amend the commit to resolve the conflict and update the commit message. After making the changes, force-push the updated commit.
> 
> Screenshot from 2024-11-29 15-43-24
> 
> The highlighted text should be moved to the commit title and follow the [Conventional Commits guideline](https://www.conventionalcommits.org/en/v1.0.0/).

Thanks @esmaeil-ahmadipour . I updated the commit and restructured the directories

**Comment by esmaeil-ahmadipour** [comment]
I had a look at the implementation compared to the Figma design.

The goal for this issue was to create a simple sitemap based on the design, but the current implementation seems incomplete.

All pages were expected to be mocked with navigation between them, but only two pages have been connected to the routing system: a splash page and a home page.

Looking at the design, there isn’t actually a page named "Home," and what’s labeled as "Splash" is more of a "Welcome" page that quickly navigates to the next screen.

Here’s a list of all the main routes we were expecting:


## Register Route
1. **SplashScreen**  
2. **Welcome Page**  
3. **Initialize Mode**  
4. **Restoration Seed**  
5. **Confirmation Seed**  
6. **Master Password**  
7. **Validator Config**  
8. **Initializing**  
9. **Finish**  

## Basic Route
1. **SplashScreen**  
2. **Password**  
3. **Dashboard**  

----

@phoenixit99

**Comment by phoenixit99** [comment]
> I had a look at the implementation compared to the Figma design.
> 
> The goal for this issue was to create a simple sitemap based on the design, but the current implementation seems incomplete.
> 
> All pages were expected to be mocked with navigation between them, but only two pages have been connected to the routing system: a splash page and a home page.
> 
> Looking at the design, there isn’t actually a page named "Home," and what’s labeled as "Splash" is more of a "Welcome" page that quickly navigates to the next screen.
> 
> Here’s a list of all the main routes we were expecting:
> 
> ## Register Route
> 1. **SplashScreen**
> 2. **Welcome Page**
> 3. **Initialize Mode**
> 4. **Restoration Seed**
> 5. **Confirmation Seed**
> 6. **Master Password**
> 7. **Validator Config**
> 8. **Initializing**
> 9. **Finish**
> 
> ## Basic Route
> 1. **SplashScreen**
> 2. **Password**
> 3. **Dashboard**
> 
> @phoenixit99

Already apply in new PR

**Comment by phoenixit99** [comment]
> I’ve added 5 comments as a reviewer on certain parts of your code.
> 
> Whenever you get a time , please take a look at them directly in the PR so I don’t need to rewrite them for you.
> 
> To make things easier for you this time, I’ve summarized all the points here as new comments. please review and take action on them whenever possible.
> 
> Let me know once everything is resolved. Thanks so much!
> 
> ## Problems :
> `#1` : in this file : `lib/presentation/bloc/language_bloc/language_bloc.dart` in this line : `4`
> 
> ```
> const languagePrefsKey = 'languagePrefs';
> ```
> 
> please if don't use remove it.
> 
> `#2` : in this file : `lib/src/core/router/app_router.dart` in this part: all this parts used for register route. we need another route for basic route. so create two file one for basic route and another for registration route. and consume two routes in this file. (in future need move any route parts to self modules.)
> 
> `#3` : in this file : `lib/src/features/splash/presentation/screen/splash_screen.dart` in this line : `50`
> 
> ```
>                 const SizedBox(height: _spacingBetweenElements),
> ```
> 
> please add Gap package and use it and replace with SizedBox
> 
> `#4` : in this file : `lib/src/core/router/route_name.dart` in this line : `14 ~ 26`
> 
> ```
>   String get path => switch (this) {
>         AppRoute.splash => '/',
>         AppRoute.dashboard => '/dashboard',
>         AppRoute.password => '/password',
>         AppRoute.welcome => '/welcome',
>         AppRoute.initializeMode => '/initialize-mode',
>         AppRoute.restorationSeed => '/restoration-seed',
>         AppRoute.confirmationSeed => '/confirmation-seed',
>         AppRoute.masterPassword => '/master-password',
>         AppRoute.validatorConfig => '/validator-config',
>         AppRoute.initializing => '/initializing',
>         AppRoute.finish => '/finish',
>       };
>       
> ```
> 
> remove this part and write easy way :)
> 
> ```
> /// Returns the route path for this enum value.
> String get routePath => '/$name';
> ```
> 
> `#5` : in this file : `lib/src/core/router/route_name.dart` in this line : `28~ 40`
> 
> ```
>   String get name => switch (this) {
>         AppRoute.splash => 'splash',
>         AppRoute.dashboard => 'dashboard',
>         AppRoute.password => 'password',
>         AppRoute.welcome => 'welcome',
>         AppRoute.initializeMode => 'initializeMode',
>         AppRoute.restorationSeed => 'restorationSeed',
>         AppRoute.confirmationSeed => 'confirmationSeed',
>         AppRoute.masterPassword => 'masterPassword',
>         AppRoute.validatorConfig => 'validatorConfig',
>         AppRoute.initializing => 'initializing',
>         AppRoute.finish => 'finish',
>       };
>       
> ```
> 
> remove this part and write easy way :)
> 
> ```
> and for this write :
> 
> /// Returns the route name for this enum value.
> String get routeName => name;
> ```
> 
> @phoenixit99

Thanks for your comment, I update the code

**Comment by esmaeil-ahmadipour** [comment]
@phoenixit99  , henry excellent. good job!

Please add a button to all screens to navigate forward through the flow until the end. Make sure users can go back to previous screens, and ensure the last screen (when navigating back) is the first screen of the route, not the splash screen.

- **registrationRoutes:** The first screen should be `Welcome`.  
- **basicRoutes:** The first screen should be `BasicPassword`.

**Pull request merged**
